"""
WriteAcademy ITS v2.0 — Pydantic Data Models
Covers: learner profiles, story structure, session planning, skill assessment.
See skills/story-data-model.md for Firestore schema (file-based for hackathon MVP).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ─── Enums ────────────────────────────────────────────────────────────────────


class SkillLevel(str, Enum):
    NOT_ASSESSED = "not_assessed"
    DEVELOPING = "developing"
    COMPETENT = "competent"
    STRONG = "strong"


class TechniqueMode(str, Enum):
    FULL = "full"
    COMPRESS = "compress"
    SKIP = "skip"


# ─── Skill Assessment ─────────────────────────────────────────────────────────


class SkillAssessment(BaseModel):
    """One craft dimension assessed from a writing sample."""
    dimension: str          # e.g. "sensory_detail", "character_voice"
    level: SkillLevel
    evidence: str           # quote from writing sample that informed the rating
    recommendation: TechniqueMode


# ─── Learner Profile ──────────────────────────────────────────────────────────


class LearnerProfile(BaseModel):
    """Persistent learner model: skills, preferences, history."""
    uid: str
    display_name: str
    skill_levels: dict[str, SkillLevel] = Field(
        default_factory=lambda: {
            "sensory_detail": SkillLevel.NOT_ASSESSED,
            "character_voice": SkillLevel.NOT_ASSESSED,
            "show_dont_tell": SkillLevel.NOT_ASSESSED,
            "story_structure": SkillLevel.NOT_ASSESSED,
            "visual_thinking": SkillLevel.NOT_ASSESSED,
        }
    )
    completed_techniques: list[str] = Field(default_factory=list)
    writing_samples: list[dict] = Field(default_factory=list)
    style_preferences: dict = Field(
        default_factory=lambda: {
            "tone": "warm",
            "genre": "picture_book",
            "learning_style": "visual",
        }
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ─── Story Models ─────────────────────────────────────────────────────────────


class StoryProject(BaseModel):
    """Top-level storybook project — the persistent creative artifact."""
    story_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    title: str
    premise: str                    # one-sentence story description
    character_name: str
    character_description: str      # visual + personality, used in illustration prompts
    world_description: str          # setting description, used in illustration prompts
    target_age: str = "4-8"
    genre: str = "picture_book"
    style_anchor: Optional[str] = None  # art style description set from first illustration
    character_visual_notes: list[str] = Field(default_factory=list)  # accumulated per-page
    environment_visual_notes: list[str] = Field(default_factory=list)  # season, weather, lighting
    current_session: int = 1
    created_at: datetime = Field(default_factory=datetime.utcnow)


class StoryPage(BaseModel):
    """One page of the storybook — text draft + illustration."""
    page_number: int
    text_draft: str
    technique_applied: Optional[str] = None
    illustration_url: Optional[str] = None   # Cloud Storage URL (or local path for MVP)
    illustration_b64: Optional[str] = None   # base64 data URL for localStorage/file fallback
    illustration_prompt: Optional[str] = None
    revision_history: list[dict] = Field(default_factory=list)  # append-only
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


# ─── Session Models ───────────────────────────────────────────────────────────


class TechniqueAdaptation(BaseModel):
    """One craft technique with its adaptive treatment for this session."""
    name: str
    mode: TechniqueMode
    reason: str             # why this mode was chosen (shown to learner briefly)


class SessionPlan(BaseModel):
    """
    Adaptive plan for one 25-minute Pomodoro session.
    Generated by Gemini based on LearnerProfile + StoryProject state.
    """
    session_number: int
    title: str              # e.g. "The Opening" (Session 1)
    story_beat: str         # narrative prompt for this session
    target_pages: list[int]  # page numbers to write this session (e.g. [1, 2, 3])
    techniques: list[TechniqueAdaptation]
    wonder_prompt: str      # Act 1: opening example/question (not "Today we learn X")
    wonder_example: str     # Act 1: published children's book passage to analyse
    build_instructions: str # Act 2: fallback writing prompt with story context
    page_prompts: list[str] = Field(default_factory=list)  # Act 2: one prompt per target page
    reflect_preview: str    # Act 3: next-session hook (story-specific cliffhanger)


class SessionRecord(BaseModel):
    """Immutable record written after a session completes."""
    session_number: int
    pages_written: list[int]
    techniques_practiced: list[str]
    techniques_skipped: list[str]
    coach_feedback_summary: Optional[str] = None
    duration_minutes: Optional[float] = None
    completed_at: datetime = Field(default_factory=datetime.utcnow)


# ─── Onboarding ───────────────────────────────────────────────────────────────


class OnboardingResult(BaseModel):
    """
    Full result from POST /onboard.
    Combines skill assessment with story setup and a ready-to-use profile.
    """
    uid: str
    skills: list[SkillAssessment]
    overall_level: str          # "beginner" | "intermediate" | "advanced"
    suggested_focus: str        # one-sentence coaching priority for this learner
    story: StoryProject
    profile: LearnerProfile
    session_plan: Optional[SessionPlan] = None  # pre-generated Session 1 plan


# ─── API Request / Response Models ───────────────────────────────────────────


class OnboardRequest(BaseModel):
    """POST /onboard — everything collected during the onboarding flow."""
    uid: str                        # client-generated UUID stored in localStorage
    display_name: str
    writing_sample: str             # ~150 word story opening
    story_title: str
    character_name: str
    character_description: str      # appearance + personality
    world_description: str          # setting
    premise: str                    # one-sentence story description
    target_age: str = "4-8"


class SessionPlanRequest(BaseModel):
    """POST /session/plan — generate or regenerate an adaptive session plan."""
    uid: str
    story_id: str
    session_number: int = 1


class StoryPageSaveRequest(BaseModel):
    """POST /story/page — save a draft (and optionally trigger illustration)."""
    uid: str
    story_id: str
    page_number: int
    text_draft: str
    technique_applied: Optional[str] = None
    trigger_illustration: bool = True


class IllustrateRequest(BaseModel):
    """POST /story/page/illustrate — generate or regenerate one page illustration."""
    uid: str
    story_id: str
    page_number: int
    text_draft: str
    # Story context for style consistency
    title: str
    character_name: str
    character_description: str
    world_description: str
    style_anchor: Optional[str] = None         # None on page 1 (we set it here)
    character_visual_notes: list[str] = Field(default_factory=list)


class IllustrateResponse(BaseModel):
    """Response from POST /story/page/illustrate."""
    page_number: int
    illustration_b64: str           # data:image/png;base64,...
    style_anchor: Optional[str] = None  # populated when first page is illustrated
    character_visual_notes: list[str] = Field(default_factory=list)
    environment_visual_notes: list[str] = Field(default_factory=list)


class CoachFeedbackRequest(BaseModel):
    """POST /coach/feedback — streaming coach feedback on a draft in story context."""
    uid: str
    draft_text: str
    technique: str
    page_number: int
    story_title: str
    prior_pages: list[dict] = Field(default_factory=list)  # [{page_number, text_draft}]


class ExportRequest(BaseModel):
    """POST /story/export — assemble illustrated storybook as PDF."""
    uid: str
    story_id: str


# ─── Gibbs Session Feedback ──────────────────────────────────────────────────


class GibbsFeedbackPhase(BaseModel):
    """One phase of Gibbs-structured writing feedback."""
    phase: str              # description, feelings, evaluation, analysis, conclusion, action_plan
    title: str
    content: str            # 2-3 sentences with specific quotes from their writing


class SessionFeedback(BaseModel):
    """Holistic Gibbs-cycle feedback generated at the end of a session."""
    session_number: int
    phases: list[GibbsFeedbackPhase]
    overall_summary: str    # 1 encouraging sentence


class SessionFeedbackRequest(BaseModel):
    """POST /coach/session-feedback."""
    uid: str
    story_id: str
    session_number: int
